export class suspiciousVehiclesModel {
    public vehicleId: number;
    public vehicleName: string;
    public rcNumber: string;
    public registrationDate: Date;
    public ownerName: string;
    public ownerContactNumber: string;
    public createdDate: Date;
    public cityName: string;
    public serialNumber: string;
    public isOwner: boolean;
    public isDeviceMapped: boolean;
    public cityId: number;
    public districtId: number;
    public districtName: string;
    public rcExpiryDate: Date;
    public stateId: number;
    public stateName: string;
    public deviceMappedDate: Date;
    public engineStatus: string;
    public ignitionStatus: string;
    public imeiNumber: string;
    public langitude: string;
    public latitude: string;
    public location: string;
    public movement: string;
    public status: string;
    public watchId: string;
}
