spring:
  profiles:
    active: qa

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    org.hibernate: INFO

server:
  port: 9999
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore.tomcat
    key-store-password: 123456789
    key-password: 123456789